### ISSUE TITLE
`undefined` output?

### ISSUE THREAD

**Issue by leeola** [shanejonas/grunt-browserify2#1]
Couple questions. Below is my config:

``` CoffeeScript
    browserify2:
      entry: 'build/client/main.js'
      mount: '/static/javascript/main.js'
      compile: 'build/public/main.js'
      debug: true
```
1. My `build/public/main.js` equals `undefined`. That is to say, the entire contents are `undefined`, and nothing more. Thoughts?
2. If i don't include the `mount` option, it errors out telling me that it is a require parameter. Why is it required? I want to compile the js with browserify2, not run any type of server integration with browserify & express. Thoughts?

Also, my apologies if you just posted this an hour ago haha. I saw the result via Google. I felt a little bad for posting an issue immediately :s

**Comment by leeola** [comment]
The answer to the first problem is simply that `entry` & `compile` don't take into account the `cwd`. Perhaps a `cwd` option should be added, and default to `process.cwd()` if it's not provided?

**Comment by shanejonas** [comment]
yep! working on that right now actually... should have something up soon.

**Comment by shanejonas** [comment]
made the fixes. bumped the version to 0.1.1 let me know if it solves all your issues.

**Comment by leeola** [comment]
Yup, looks great! When you have time, please checkout my comment on #2 about a success message of some sort.

Thanks!
